// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const String webVapidKey =
      'BAwgaQfd2s_3Q97IbnVqy1alga1pjfyz3I0zTqf-J-Uw_7TqoPufj9p8a-8Gl5o3Wu-hIQunfykgYaLJDNU7NHU';

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS9MZsK5zQPQmyKZ6J2h32d3d7ANDFcts',
    appId: '1:512224138763:web:ba4c63b9009602f7cad90e',
    messagingSenderId: '512224138763',
    projectId: 'bam-wallet-eb1e7',
    authDomain: 'bam-wallet-eb1e7.firebaseapp.com',
    storageBucket: 'bam-wallet-eb1e7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeptp_pyOxfpW-v7ogilqWwcal8zP4KG0',
    appId: '1:512224138763:android:40f98cbcf1efd45ecad90e',
    messagingSenderId: '512224138763',
    projectId: 'bam-wallet-eb1e7',
    storageBucket: 'bam-wallet-eb1e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwb4GEX3PxBeTOpwSqyptcZlVwVd8o134',
    appId: '1:512224138763:ios:015474ba9c9d06dacad90e',
    messagingSenderId: '512224138763',
    projectId: 'bam-wallet-eb1e7',
    storageBucket: 'bam-wallet-eb1e7.firebasestorage.app',
    iosBundleId: 'com.example.bamWallet',
  );
}