// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const String webVapidKey =
      'BHF4K9usq3IDrt5ibo5gnvMJEc2bq3SM4eqv__gg3FSII9ekJTgqpcpBgu01XKfrInOsAuVR5nJeEHVJumxf2Hg';

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2uS7RDsD0tWkR1KR8p5hBV-7mNuEW0ew',
    appId: '1:599905481724:web:f250979bee6e24943f3879',
    messagingSenderId: '599905481724',
    projectId: 'bam-wallet-4995c',
    authDomain: 'bam-wallet-4995c.firebaseapp.com',
    storageBucket: 'bam-wallet-4995c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkNCM_oFz_zL_OyDMGyGjmO7AeWgNYjjk',
    appId: '1:599905481724:android:873b8cafa2a768c73f3879',
    messagingSenderId: '599905481724',
    projectId: 'bam-wallet-4995c',
    storageBucket: 'bam-wallet-4995c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATXemqbDPk6MPm23gILkEGjSWVyydV0fc',
    appId: '1:599905481724:ios:c7722e849776fdec3f3879',
    messagingSenderId: '599905481724',
    projectId: 'bam-wallet-4995c',
    storageBucket: 'bam-wallet-4995c.firebasestorage.app',
    iosBundleId: 'com.example.bamWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATXemqbDPk6MPm23gILkEGjSWVyydV0fc',
    appId: '1:599905481724:ios:c7722e849776fdec3f3879',
    messagingSenderId: '599905481724',
    projectId: 'bam-wallet-4995c',
    storageBucket: 'bam-wallet-4995c.firebasestorage.app',
    iosBundleId: 'com.example.bamWallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2uS7RDsD0tWkR1KR8p5hBV-7mNuEW0ew',
    appId: '1:599905481724:web:94ac1f1776cb87433f3879',
    messagingSenderId: '599905481724',
    projectId: 'bam-wallet-4995c',
    authDomain: 'bam-wallet-4995c.firebaseapp.com',
    storageBucket: 'bam-wallet-4995c.firebasestorage.app',
  );
}
