name: bam_wallet
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you w
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_approuter: ^3.0.5
  flutter_localizations:
    sdk: flutter
  go_router: ^17.1.0
  http: ^1.1.0
  intl: ^0.20.2
  local_auth: ^2.3.0
  package_info_plus: ^8.0.0
  provider: ^6.0.0
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.0
  flutter_riverpod: ^2.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/env/
